[project]
name = "spark-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.3.5",
    "pandas>=2.2.3",
    "pyarrow>=19.0.0",
    "pyspark>=3.5.4",
    "setuptools>=75.8.0",
]
